# sudo is true so we can run the spell_check binary
sudo: true
language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
before_install: chmod +x spell_check
install: pip install -r requirements.txt
script: tox