version: '3.1'
services:
    appsec:
        restart: "no"
        build: .
        ports:
            - 8080:5000
        secrets:
            - key_secret
            - admin_phone
            - admin_password
    demo:
        image: appsec_appsec
        deploy:
            replicas: 4
        networks:
            - mynet
networks:
  mynet:
    driver: overlay

secrets:
  key_secret:
    file: key_secret.txt
  admin_phone:
    file: admin_phone.txt
  admin_password:
    file: admin_password.txt