version: '3.1'
services:
    appsec:
        restart: "no"
        build: .
        ports:
            - 8080:5000
        secrets:
            - my_secret
secrets:
  my_secret:
    file: my_secret.txt