version: '3.1'
services:
    appsec:
        restart: "no"
        build: .
        ports:
            - 5000
        secrets:
            - key_secret
            - admin_phone
            - admin_password
secrets:
  key_secret:
    file: key_secret.txt
  admin_phone:
    file: admin_phone.txt
  admin_password:
    file: admin_password.txt